### ISSUE TITLE
this icp could be used for 2D data?

### ISSUE THREAD

**Issue by rebeen** [agnivsen/icp#1]
could you please tell me whether this algorithm could be used to align two TSNE data which are 2d or not ?

best regards
rebeen

**Comment by agnivsen** [comment]
Hi Rebeen,


Thanks for reaching out to me. I appreciate your interest in my code.

When you say TSNE data, I hope you are referring to t-Distributed Stochastic Neighbor Embedding. However, I must admit I do not know much about t-SNE.

The code is supposed to work with 3D data points as input. It is supposed to register two set of 3D data points, provided that the distance between the data points can be interpreted in an Eucledian sense. (I am not sure if that applies to t-SNE or not. Perhaps, you would know better.) 

However, it can be made to work with 2D data points with some minor modifications. Perhaps, I would try to add that feature in a future update. If you wish to try it yourself, you can begin by changing the input to the 'icp_point_to_point_lm' method.

Hope this helps. Do reply back if you have some more questions/comments.


Best Regards,
Agniv Sen.

**Comment by rebeen** [comment]
Hi Agnivsen,
thank you for your answer, yes I meant  t-Distributed Stochastic Neighbor Embedding data, so I have two       t-SNE 2D data and I want to apply icp to align them , I will check your code but I do not have enough experience to update your code, or if you want we can do that together,

Best regards,
Rebeen

**Comment by agnivsen** [comment]
Hi Rebeen,

Sure, we can do that together.

There's a quick and easy way to get the code working on 2D data. This is quite simple but slightly hacky, so please be warned. However, here's what I suggest we initially do:

Append a third dummy dimension to your data.

Let us say you have a 2D data which looks like this:
x1, y1
x2, y2
x3, y3
.
.
.
xn, yn

Add a third dimension to it, which should be a constant value (say 1). So your data becomes:

x1, y1, 1
x2, y2, 1
x3, y3, 1
.
.
.
xn, yn, 1

Do this to both the datasets you have (add third dimension of all 1s). Put these two dataset in the .xyz files, as explained in the ReadMe. Call icp_point_to_point_lm method with these two dataset. 

Should work fine without any code changes. However, like I said before, this is not very elegant. I will look into code changes for 2D data later, should be straightforward. 

Please feel free to contribute in whichever way it suits you. Please let me know if this works.

Regards,
Agniv.

**Comment by rebeen** [comment]
thank you very much I will try to do that 
best regards,
we may get a help form this https://github.com/ClayFlannigan/icp
rebeen
