### ISSUE TITLE
how to understand your residual equation?

### ISSUE THREAD

**Issue by wenbowen123** [agnivsen/icp#2]
Your rotation is represented by Euler angle, but you directly multiply them with other variables, what does that mean? 

And it seems like you are doing cross product between normal vector and source point, should it be inner product instead so as to compute distance?

**Comment by agnivsen** [comment]
A brief, but not well formatted explanation of the maths behind the code can be found in the following document:
[A rough documentation of ICP](https://github.com/agnivsen/icp/files/1987104/ICP_concepts.pdf)

Please note that these equations were devoured off a scratch pad and may include many abuses of mathematical notation and are definitely not in the same sequence as in the Python code. But I hope it will answer your first question.

As for the second question, can you please help me to the specific line number of the code (in '_basicICP.py_', I presume) where you see the cross product that troubles you.

**Comment by wenbowen123** [comment]
@agnivsen 

Here is the line. I think there is some problem...
        _residual = (alpha*a1) + (beta*a2) + (gamma*a3) + (nx*tx) + (ny*ty) + (nz*tz) - (((nx*dx) + (ny*dy) + (nz*dz)) - ((nx*sx) + (ny*sy) + (nz*sz)))

**Comment by wenbowen123** [comment]
@agnivsen 
https://github.com/agnivsen/icp/blob/f16b0cacb1cbabf5d69eba98c7476daf1f77f4ac/basicICP.py#L261

**Comment by agnivsen** [comment]
Please refer to the appendix of the PDF file I shared, the formulation of the residual is described there. 

It is not a cross product. It is just the dot product, expressed in a slightly simplified form.

Does that answer your question?

**Comment by wenbowen123** [comment]
@agnivsen em... it's actually cross product if you plug into the variables. it contains a cross product of two vectors and inner product with normal vector.

**Comment by agnivsen** [comment]
No, it can be expressed as a sum of cross product of two vectors added to a set of dot products of the normal with the translation vector and the points themselves. It can be represented as that, yes. But does it make any sense? Moreover, the first vector you see in the cross product is a vector of Euler angles and not Lie algebra. So it makes even less sense to think of it in that way.

However, it has been derived from something much simpler. Check the derivation. It is the dot product of the normal vector with the vector from one point to another (based on the estimate of transformation).

**Comment by wenbowen123** [comment]
@agnivsen that makes more sense. Thats also why I wonder why you are doing this given that they are not  Lie algebra. Now its more clear. Thanks

**Comment by agnivsen** [comment]
Cheers. :)
