### ISSUE TITLE
2D/3D plot diagram

### ISSUE THREAD

**Issue by Jiaxin-lim** [agnivsen/icp#4]
Hi, i came across your work on ICP for python.

I have tried running it however the results are given in numbers instead of plot diagram. Is there any ways the points can be plotted out into a visual diagram?

Look forward to your reply soon.

Thank you.

**Comment by agnivsen** [comment]
Hi Jiaxin-lim,

Thanks for your question.

Unfortunately, there is no mechanism to plot the transformation matrix. Indeed, the code is lacking a visualizer.

I may suggest using a combination of [MeshLab](https://www.meshlab.net/) (to transform the mesh with the output of ICP) and [CloudCompare](https://www.danielgm.net/cc/) (to plot the quality of registration) to obtain a quantitative analysis of the output. However, we do not plan to update this code at the moment, sorry about that.

Let me know if you need anything else.

(May I close this issue?)

 Best Regards, 
Agniva
