### ISSUE TITLE
how to get point correspondence

### ISSUE THREAD

**Issue by ynma-hanvo** [agnivsen/icp#9]
hello.  thanks for share your icp work. 
but this is difference from the  icp which can work  on two set of different pointclouds.
so how do i get the point correspondence between two different cloud is the problem

**Comment by ynma-hanvo** [comment]
@agnivsen please give some suggestion

**Comment by agnivsen** [comment]
Hi ynma-hanvo,

So if I understood correctly, your question is: 'how to get point correspondence' between two arbitrary pointcloud?

Did I understand the question correctly?

Best regards,
Agniva

**Comment by ynma-hanvo** [comment]
> Hi ynma-hanvo,
> 
> So if I understood correctly, your question is: 'how to get point correspondence' between two arbitrary pointcloud?
> 
> Did I understand the question correctly?
> 
> Best regards, Agniva

yes. you are right.  (and  does it works if my src and dest  pointclouds only have partial overlaps).

**Comment by agnivsen** [comment]
Hi ynma-hanvo,

The input to ICP, in the provided examples in this repository, does not require correspondence.

It does, however, require an initial estimate of the transformation between the two pointclouds, if you want to avoid spurious local minima. 

Sorry, the current implementation only handles cases where the number of 3D points are the same in source and destination pointcloud. But it is easy to extend this to handle partial overlaps. Unfortunately, this is just a toy example and is not currently being maintained/updated any longer. But feel free to extend it, if you wish.

_(If your question was about general pointcloud registration, I would suggest the [Wikipedia article](https://en.wikipedia.org/wiki/Point-set_registration) as a good starting point)_

Best regards,
Agniva

**Comment by ynma-hanvo** [comment]
thanks.   I will do more research on ICP. 

you mean   in  the  icp_point_to_point_lm    code, 

    for i in range (0, N):
        
        #print dest_points[i][3],dest_points[i][4],dest_points[i][5]
        dx = dest_points[i][0]
        dy = dest_points[i][1]
        dz = dest_points[i][2]
        
        sx = source_points[i][0] #i can use    N - i here ?
        sy = source_points[i][1]
        sz = source_points[i][2]
        

the same index is not neccessary? am I right

**Comment by agnivsen** [comment]
No sorry, in this example, the input is essentially 1 point cloud (source_points) and its deformed variant (dest_points), so the correspondence inside this loop is automatically maintained. This was done to demonstrate the GN/LM update strategy, not the full implementation of ICP.

If you want a proper implementation of a correspondence free ICP, do the following:

1. In <icp_point_to_point_lm>, right above L166, add a code for nearest neighborhood finding 
2. You can do this efficiently using [KD-tree](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.query.html) or simply with an Euclidean distance based sorting, e.g.: in this [Q&A](https://stackoverflow.com/a/72546215/2041826)

The objective is to have two point clouds <source_points> and <dest_points>, where each point index in the point clouds are in correspondence with each other only if they are their nearest neighbors.

Hope this helps.

Cheers,
Agniva

**Comment by ynma-hanvo** [comment]
thanks for clarify.   I learned much from your code.
